--- 
abstract: Provide $self and @args variables for OO programs
author: 
  - Audrey Tang <cpan@audreyt.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: mit
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: selfvars
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.004
version: 0.01
